server:
  port: 8808

spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #腾讯云数据库
    url: jdbc:mysql://193.112.79.59:3308/smart?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: select 1
  #配置自动建表：update：没有表新建，有表更新，控制台显示建表语句
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
  #防止JPA查询报错
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#mybatis
mybatis:
  type-aliases-package: com.cn.smart.jpa.entity
  mapper-locations: classpath:mybatis/**/*.xml

#配置日志
#logging:
#  com.fishpro.log: debug
#  #指定输出文件的存储路径(自动创建目录和文件)
#  file: logs/debug.log
#  #指定日志输出格式
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"

