---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuwei.
--- DateTime: 2024/12/20 17:43
---

-- 降序排列数组
--t = {3, 2, 5, 1, 4}
--table.sort(t, function(a, b)
--    return a > b
--end)
---- 自定义的打印数组的函数
--printArray(t) -- [5, 4, 3, 2, 1]


print("Hello, World!")